apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: logging
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  clusterIP: None
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
    name: db1
  - port: 9300
      protocol: TCP
      targetPort: transport
      name: transport1
  selector:
    k8s-app: elasticsearch-logging
